# config/valid_insurers.py

VALID_INSURERS = [
    "Advanced Insurance Consultants Ltd",
    "AIG",
    "Alan Boswell Group",
    "Alice Castle Ltd",
    "Allianz Global",
    "Aon",
    "Aro Insurance",
    "Aviva",
    "AXA",
    "Chiswell Insurance",
    "Chubb European",
    "Churchill Insurance",
    "CNA Hardy",
    "Covea Insurance",
    "Direct Line",
    "Equipsme Health Insurance",
    "Finsbury Insurance",
    "HDI",
    "Hiscox",
    "Howden Group",
    "Liberty Mutual",
    "Lloyds Banking Group",
    "Maltings Insurance",
    "Manchester Underwriting",
    "Markel Direct",
    "Marsh",
    "Martinez & Partners Ltd",
    "McParland Finn Ltd",
    "Meadow Broking Limited",
    "MGB Insurance Brokers",
    "Modus Insurance",
    "New Dawn Risk Group",
    "NIG Insurance",
    "Northern Alliance Brokers Limited",
    "Onyx Insurance Brokers Limited",
    "Paul Evans ACII, Chartered Insurance Broker",
    "Pen Underwriting Insurance",
    "Perkins Slade Ltd",
    "QBE",
    "Royal and Sun Alliance",
    "Sompo International",
    "Tokio Marine HCC",
    "Travelers Insurance",
    "Zurich",
    "Other"
]